/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_compeople_commons_net_winhttp_WinHttp */

#ifndef _Included_de_compeople_commons_net_winhttp_WinHttp
#define _Included_de_compeople_commons_net_winhttp_WinHttp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_compeople_commons_net_winhttp_WinHttp
 * Method:    open
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_de_compeople_commons_net_winhttp_WinHttp_open
  (JNIEnv *, jclass, jstring, jint, jstring, jstring, jint);

/*
 * Class:     de_compeople_commons_net_winhttp_WinHttp
 * Method:    closeHandle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_compeople_commons_net_winhttp_WinHttp_closeHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_compeople_commons_net_winhttp_WinHttp
 * Method:    getIEProxyConfigForCurrentUser
 * Signature: (Lde/compeople/commons/net/winhttp/WinHttpCurrentUserIEProxyConfig;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_compeople_commons_net_winhttp_WinHttp_getIEProxyConfigForCurrentUser
  (JNIEnv *, jclass, jobject);

/*
 * Class:     de_compeople_commons_net_winhttp_WinHttp
 * Method:    getProxyForUrl
 * Signature: (ILjava/lang/String;Lde/compeople/commons/net/winhttp/WinHttpAutoProxyOptions;Lde/compeople/commons/net/winhttp/WinHttpProxyInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_compeople_commons_net_winhttp_WinHttp_getProxyForUrl
  (JNIEnv *, jclass, jint, jstring, jobject, jobject);

/*
 * Class:     de_compeople_commons_net_winhttp_WinHttp
 * Method:    getLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_compeople_commons_net_winhttp_WinHttp_getLastError
  (JNIEnv *, jclass);

/*
 * Class:     de_compeople_commons_net_winhttp_WinHttp
 * Method:    getLastErrorMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_compeople_commons_net_winhttp_WinHttp_getLastErrorMessage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
